services:
  odd_id_generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odd_id_generator
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://user:password@db_odd:5432/odd_db
      - SEQUENCE_NAME=odd_sequence
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001" ]
    ports:
      - "8001:8000"
    depends_on:
      - db_odd

  even_id_generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: even_id_generator
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002" ]
    environment:
      - PORT=8002
      - DATABASE_URL=postgresql://user:password@db_even:5432/even_db
      - SEQUENCE_NAME=even_sequence
    ports:
      - "8002:8000"
    depends_on:
      - db_even

  db_odd:
    image: postgres:13
    container_name: odd_id_gen_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: odd_db
    ports:
      - "5433:5432"
    volumes:
      - ./init_odd_sequence.sql:/docker-entrypoint-initdb.d/init_odd_sequences.sql

  db_even:
    image: postgres:13
    container_name: even_id_gen_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: even_db
    ports:
      - "5434:5432"
    volumes:
      - ./init_even_sequence.sql:/docker-entrypoint-initdb.d/init_even_sequences.sql

  load_balancer:
    image: nginx:latest
    container_name: unique_id_gen_lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - odd_id_generator
      - even_id_generator
